### ISSUE TITLE
aspectra "make aips2sqlite" fails

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/aips2sqlite#19]
1. Set path in `.bash_profile` to `export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64`
2. cd `aips2sqlite`
3. type `make aips2sqlite`
4. Fails with
```
./gradlew jar 
Downloading https://services.gradle.org/distributions/gradle-5.0-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
make: *** [aips2sqlite] Error 1
```
5. Looks like a Download restriction.

**Comment by zdavatz** [comment]
Ich versuche: 
`/usr/lib/jvm/jre/bin/java -DproxySet=true -Dhttp.proxyHost=172.16.0.1 -Dhttp.proxyPort=8080 make aips2sqlite`

**Comment by tgubser** [comment]
```
  export http_proxy=http://172.16.0.1:8080
  export https_proxy=http://172.16.0.1:8080
```

**Comment by zdavatz** [comment]
Ich versuche jetzt:
`./gradlew -Dhttp.proxyHost=http://172.16.0.1 -Dhttp.proxyHost=https://172.16.0.1 -Dhttp.proxyPort=8080 jar`

**Comment by zdavatz** [comment]
next:
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre contains a valid JDK installation.
```

**Comment by zdavatz** [comment]
@tgubser adapted Makefile to: 
`./gradlew -Dhttp.proxyHost=172.16.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=172.16.0.1 -Dhttps.proxyPort=8080 jar $(ARGS)`
works now.
