### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/aips2sqlite#30]
Ich mache:
```
cd /home/zeno/.software/aips2sqlite
git pull
cd /home/zeno/.software/aips2sqlite/jars
/usr/local/src/jre1.8.0_101/bin/java -jar -Xmx6000m /home/zeno/.software/aips2sqlite/jars/aips2sqlite.jar --owner=Axapharm --plain --xml --lang=de --pinfo
```
und erhalte
```
- Processing packages xlsx... Exception in thread "main" java.lang.IllegalStateException: Cannot get a text value from a numeric cell
        at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:845)
        at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:294)
        at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:246)
        at com.maxl.java.aips2sqlite.RealPatientInfo.extractPackageInfo(RealPatientInfo.java:159)
        at com.maxl.java.aips2sqlite.RealPatientInfo.process(RealPatientInfo.java:501)
        at com.maxl.java.aips2sqlite.Aips2Sqlite.generateSQLiteDB(Aips2Sqlite.java:360)
        at com.maxl.java.aips2sqlite.Aips2Sqlite.main(Aips2Sqlite.java:334)
```

**Comment by zdavatz** [comment]
Ich denke, das ist die die Problem-Datei: https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx

Ich bin gespannt, welche Spalte es ist.

**Comment by phwiget** [comment]
Danke Zeno

**Comment by zdavatz** [comment]
![swissmedic_packages_xlsx 2020-06-10 01-39-01](https://user-images.githubusercontent.com/4953/84178683-194bed00-aa85-11ea-86c6-05134e1ba095.jpg)

Das Problem ist in "swissmedic_packages_xlsx.xlsx", Zeile 10326, Spalte M

**Comment by zdavatz** [comment]
@phwiget bitte mach 
1. `make aips2sqlite` im src dir von aips2sqlite
2. dann die Datei in `build/libs`kopieren nach `jars/aips2sqlte.jar`

**Comment by phwiget** [comment]
schaue grad an, danke dir für die schnelle Lösung!

**Comment by phwiget** [comment]
Klappt wieder, automatischer git pull heute Nacht hat funktioniert!

**Comment by zdavatz** [comment]
so muss es sein ;)

**Comment by zdavatz** [comment]
Zudem habe ich den Fehler auch der Swissmedic gemeldet und die haben sofort ein neues File publiziert. Gute Zusammenarbeit im public domain!
