### ISSUE TITLE
error when downloading AIPS 

### ISSUE THREAD

**Issue by phwiget** [zdavatz/aips2sqlite#32]
Hi Zeno

When I run the command:
```java -jar -Xmx6000m /opt/aips2sqlite-master/jars/aips2sqlite.jar --owner=Axapharm --plain --xml --lang=de --pinfo```

This error is thrown:
```
- Downloading AIPS file... - Exception: in 'downAipsXml'
com.gargoylesoftware.htmlunit.ElementNotFoundException: elementName=[*] attributeName=[name] attributeValue=[ctl00$MainContent$btnOK]
        at com.gargoylesoftware.htmlunit.html.HtmlPage.getElementByName(HtmlPage.java:1708)
        at com.maxl.java.aips2sqlite.AllDown.downAipsXml(AllDown.java:105)
        at com.maxl.java.aips2sqlite.Aips2Sqlite.allDown(Aips2Sqlite.java:391)
        at com.maxl.java.aips2sqlite.Aips2Sqlite.main(Aips2Sqlite.java:226)
```

Can you have a look at it?

**Comment by zdavatz** [comment]
Yes, they changed one Pop-Up Window.

**Comment by zdavatz** [comment]
@phwiget please do a git pull and try again. It should work now.

**Comment by phwiget** [comment]
perfect, download works again! thank you 👍
