### ISSUE TITLE
Cannot get a text value from a numeric cell

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/aips2sqlite#38]
1. Running this command: `java -jar -Xmx7048m build/libs/aips2sqlite.jar --lang=fr --xml`
2. There seems to be an issue with SwissmedicPackungen.xlsx
```
>> ERROR: 4460 - SwissmedicNo5 not found in Swissmedic Packungen.xls - (62257) Zolédronate Axapharm Ostéo 5, Solution pour perfusion
Exception in thread "main" java.lang.IllegalStateException: Cannot get a text value from a numeric cell
        at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:845)
        at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:294)
        at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:246)
        at com.maxl.java.aips2sqlite.BaseDataParser.parseSwissmedicPackagesFile_Gtin(BaseDataParser.java:167)
        at com.maxl.java.aips2sqlite.SwissMedSequences.process(SwissMedSequences.java:180)
        at com.maxl.java.aips2sqlite.Aips2Sqlite.main(Aips2Sqlite.java:271)
```

**Comment by zdavatz** [comment]
this seems to be a similar problem:
```
Zolédronate Axapharm Ostéo 5, Solution pour perfusion
Exception in thread "main" java.lang.IllegalStateException: Cannot get a text value from a numeric cell
   at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:845)
   at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:294)
   at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:246)
   at com.maxl.java.aips2sqlite.BaseDataParser.parseSwissmedicPackagesFile_Gtin(BaseDataParser.java:172)
   at com.maxl.java.aips2sqlite.SwissMedSequences.process(SwissMedSequences.java:180)
   at com.maxl.java.aips2sqlite.Aips2Sqlite.main(Aips2Sqlite.java:271)
mv: cannot stat ‘swiss_medic_sequences.csv’: No such file or directory
/opt/ywesee/generate_aips_fi: line 13: cd: /opt/ywesee/aips2sqlite/jars/downloads/tmp/unzipped_tmp: No such file or directory
```
