### ISSUE TITLE
Failed info generation

### ISSUE THREAD

**Issue by jonaspu** [zdavatz/aips2sqlite#9]
When running the `aips2sqlite.jar` we get the following exception.

```
java -jar -Xmx6000m /opt/aips2sqlite-master/jars/aips2sqlite.jar --owner=******** --plain --xml --lang=de --pinfo

- Downloading AIPS file... 1154469 kB in 54.709 sec
- Downloading Packungen file... 0 kB in 0.54 sec
- Downloading Refdata pharma file... 18874 kB in 5.468 sec
- Downloading Refdata partner file... 108132 kB in 50.124 sec
- Downloading Preparations file... 42038 kB in 1.19 sec
- Downloading Swiss DRG (DE) file... 285 kB in 0.254 sec
- Downloading Swiss DRG (FR) file... 282 kB in 0.332 sec
- Downloading EPha interactions (DE) file... 10374 kB in 0.227 sec
- Downloading EPha interactions (FR) file... 10374 kB in 0.101 sec
- Downloading EPha products (DE) file... 853 kB in 0.059 sec
- Downloading EPha products (FR) file... 853 kB in 0.019 sec
- Downloading EPha ATC codes file... 366 kB in 0.059 sec
- Downloading GLN codes file (people/personen)... 2545 kB in 13.92 sec
- Downloading GLN codes file (companies/betriebe)... 250 kB in 1.566 sec

- Generating sqlite database...
- Unmarshalling Swissmedic xml... 22072 medis in 15.037 sec
- Processing packages xlsx... Exception in thread "main" org.apache.poi.POIXMLException: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]
	at org.apache.poi.util.PackageHelper.open(PackageHelper.java:41)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:204)
	at com.maxl.java.aips2sqlite.RealPatientInfo.extractPackageInfo(RealPatientInfo.java:101)
	at com.maxl.java.aips2sqlite.RealPatientInfo.process(RealPatientInfo.java:501)
	at com.maxl.java.aips2sqlite.Aips2Sqlite.generateSQLiteDB(Aips2Sqlite.java:360)
	at com.maxl.java.aips2sqlite.Aips2Sqlite.main(Aips2Sqlite.java:334)
Caused by: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:178)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:662)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:269)
	at org.apache.poi.util.PackageHelper.open(PackageHelper.java:39)
	... 5 more
```

**Comment by zdavatz** [comment]
Thank you. Will look into it!

**Comment by zdavatz** [comment]
This file seems to be 0 bytes, but this works

`wget https://www.swissmedic.ch/dam/swissmedic/de/dokumente/listen/excel-version_zugelasseneverpackungen.xlsx.download.xlsx/excel-version_zugelasseneverpackungen.xlsx`

**Comment by zdavatz** [comment]
Swissmedic hat einen Pfad geändert.

**Comment by zdavatz** [comment]
https://dzone.com/articles/java-8-how-to-create-executable-fatjar-without-ide

**Comment by zdavatz** [comment]
`javac -d /tmp -classpath libs/\* src/com/maxl/java/aips2sqlite/*.java`

**Comment by zdavatz** [comment]
Der Link geht jetzt auch: `http://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_ham.xlsx.download.xlsx/Zugelassene_Packungen_HAM.xlsx`

**Comment by zdavatz** [comment]
läuft wieder, die Swissmedic hat die Weiterleitung repariert.

**Comment by zdavatz** [comment]
Zugelassene Packungen (Humanarzneimittel
https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_ham.xlsx

Erweiterte Liste zugelassene Humanarzneimittel
https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/erweiterte_ham.xlsx

Co-Marketing-Arzneimittel
https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/co-marketing_ham.xlsx

Humanarzneimittel mit Status Orphan Drug
https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/status_orphandrug_ham.xlsx

**Comment by zdavatz** [comment]
working with 54e3f783efb55c8f112cd78bf38126158c86fcf4
